version: '3.1'

services:
  wordpress:
    build: ../../common
    restart: always
    ports:
      - "8081:80"
    env_file:
      - ../../common/.env
    volumes:
      - ../../common/wordpress:/var/www/html
      - ../../common/plugins/woocommerce:/var/www/html/wp-content/plugins/woocommerce
      - ../../common/plugins/MOC-WP-Logger-1.0.0:/var/www/html/wp-content/plugins/MOC-WP-Logger-1.0.0
      - ./plugin/<your-plugin-name>:/var/www/html/wp-content/plugins/<your-plugin-name>
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ../../common/.env
    environment:
      MYSQL_ROOT_PASSWORD: somerootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ../../common/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

volumes:
  db_data:
