version: '3.1'

services:
  wordpress:
    build: ../../common
    restart: always
    ports:
      - "${WORDPRESS_PORT:-8081}:80"  # Port mapping for WordPress
    env_file:
      - ../../common/.env  # Environment variables for WordPress
    volumes:
      - ../../common/wordpress:/var/www/html  # WordPress core files
      - ../../common/plugins/woocommerce:/var/www/html/wp-content/plugins/woocommerce  # WooCommerce plugin
      - ../../common/plugins/MOC-WP-Logger-1.0.0:/var/www/html/wp-content/plugins/MOC-WP-Logger-1.0.0  # Logger plugin
      - ./plugin/${INSTANCE_NAME}:/var/www/html/wp-content/plugins/${INSTANCE_NAME}  # Instance-specific plugin
      - ../../common/custom-scripts:/var/www/html/custom-scripts  # Custom scripts
    depends_on:
      - db
      - mailhog
    networks:
      wordpress-network:
        aliases:
          - wordpress
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512M"

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ../../common/.env  # Environment variables for MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-exampledb}
      MYSQL_USER: ${MYSQL_USER:-exampleuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-examplepass}
    volumes:
      - db_data_${INSTANCE_NAME}:/var/lib/mysql  # Persistent storage for MySQL
      - ../../common/init.sql:/docker-entrypoint-initdb.d/init.sql  # SQL initialization script
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  # Healthcheck for MySQL
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - wordpress-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "${MAILHOG_WEB_PORT:-8025}:8025"  # MailHog Web UI
      - "${MAILHOG_SMTP_PORT:-1025}:1025"  # MailHog SMTP server
    healthcheck:
      test: ["CMD", "pgrep", "MailHog"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - wordpress-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount SSL certificates
    depends_on:
      - wordpress
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge  # Bridge network to connect services

volumes:
  db_data_${INSTANCE_NAME}:  # Volume for storing MySQL data
